Repository jenkins-x/jx-logging, pull requests merged in 2022-05, with the labels that each got.

#25 refactor: upgrade to go 1.17.9
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  Makefile
  OWNERS
  go.mod
  go.sum
Labels: size/L

#26 fix: update logging in plugin repos
  .jx/updatebot.yaml
Labels: approved, size/S

#27 refactor: enable codeql alerts
  .github/workflows/codeql-analysis.yml
Labels: size/M, lgtm, approved, ok-to-test
